#Assignment 1

##Essential Code (copy/paste to each q)

In [ ]:
import numpy as np
import math
import matplotlib.pyplot as plt

def fact(n): # RECURSIVE!!!!!!!!!!
  if n == 1: # 0! = 1!, so only need to go down to 1
    return 1
  else:
    return n*fact(n-1)

def gaussElim(A,b):
    """
    Routine to solve problem Ax = b using gauss elim.
    A is an NxN matrix, b a column vector of size N
    returns x vector of dimentsion N
    """
    # setup our augmented matrix by copying A and b
    N = A.shape[0]
    augmat = np.zeros((N, N+1))
    augmat[:,:N] = np.copy(A)
    augmat[:,N] = np.copy(b)
    
    for pivot in range(0,N):
        refrow = pivot
        for row in range(refrow+1, N):
            ratio =  augmat[row,refrow]/augmat[refrow,refrow]
            for col in range(refrow, N+1):
                augmat[row,col] = augmat[row,col] - augmat[refrow,col]*ratio
    #print(augmat)
    x = np.zeros(N)
    for row in range(N-1,-1,-1):
        x[row] = augmat[row,N] 
        for col in range(row+1, N):
            x[row] -= augmat[row,col]*x[col] 
        x[row] = x[row]/augmat[row,row]       
    return x

def lagrangePoly(myx,x,y):
  result = 0
  for i in range(len(x)):
    for j in range(len(x)):
      partResult = 1
      if (j-1)**2 <1:
        pass
      else:
        partResult *= (x-x[j])/(x[i]-x[j])
    result = partResult*y[i]
  return result

def lerp(xi,x0,y0,x1,y1):
  result = y0 +(xi-x0)*(y1-y0)/(x1-x0)
  return result

def normalise(x):
  fac = abs(x).max()
  xn = x / x.max()
  return fac, xn

def poweriterate(x,xlen):
  a = np.zeros(xlen)
  for q in range(len(xlen)):
    a[i] = 1
  for r in range(10):
    x = np.dot(a,x)
    nlambda, x = normalise(x)
  return nlambda, x

##Question 1

In [ ]:
# Defining Function
def f(x):
    return -0.955968*x**3 - 2.867905*x**2 + 9.559683*x

# Defining derivative of function
def fprime(x):
    return (3*-0.955968)*x**2 - (2*-2.867905)*x + 9.559683

def newtonRaphson(x):
    h = f(x)/fprime(x)
    while abs(h) >= 1e-15:
        h = f(x)/fprime(x)
        x = x - h
    return x

roots = []
i = -50
while i != 50:
  root = newtonRaphson(i)
  if root not in roots:
    roots.append(root)
  i+=10

roots.sort()
print(roots)


[-5.000001195497254, -5.000001195497252, 0, 1.4791141972893971e-31]


##Question 2

In [ ]:
"""This block of code creates matrix A and gives it values, 
nothing of note happens until next block"""
A = np.zeros([5,5])
A[0,0] = 3.243998
A[0,1] = 7.585622
A[0,2] = 6.244601
A[0,3] = 7.459325
A[0,4] = 4.358713

A[1,0] = 7.585622
A[1,1] = 0.706678
A[1,2] = 5.195211
A[1,3] = 0.180218
A[1,4] = 2.177688

A[2,0] = 6.244601
A[2,1] = 5.195211
A[2,2] = 0.504912
A[2,3] = 3.769038
A[2,4] = 7.096096

A[3,0] = 7.459325
A[3,1] = 0.180218
A[3,2] = 3.769038
A[3,3] = 5.370002
A[3,4] = 6.995861

A[4,0] = 4.358713
A[4,1] = 2.177688
A[4,2] = 7.096096
A[4,3] = 6.995861
A[4,4] = 4.233052


In [ ]:
At = np.transpose(A) # transpomse A atrix for matrix multiplication

In [ ]:
A2 = np.zeros([5,5]) # create matrix for result of multiplication to go in
for g in range(len(A)): # go through rows of A
  for h in range(len(At[0])): # go through columns of At
    for i in range(len(At)): # go through rows of At
      A2[g][h] += A[g][i]*At[i][h] #Result adds the multiplication of all elements in row G of A with all elements of column h in At

A2sum = 0 # create a result variable
for j in range(len(A2)): # go through rows of A2
  for k in range(len(A2)): # Go through columns of A2
    A2sum+= A2[j][k] # Add element together

print(A2sum)

2789.44338670437

##Question 3

In [ ]:
#create arrays

xi = np.array([10.000000,-8.666667,-7.333333,-6.000000,-4.666667,-3.333333,-2.000000,-0.666667,0.666667,2.000000,3.333333,4.666667,6.000000,7.333333,8.666667,10.000000])
yi = np.array([-236.858690,-179.783455,-132.915145,-92.106830,-60.370058,-31.857908,-10.878956,1.061574,4.291217,3.578033,-5.377525,-25.148321,-45.176053,-75.555361,-113.610130,-156.051823])

In [ ]:
z = np.zeros((len(xi),5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
for i in range(len(xi)):
  z[i,0] = 1
  z[i,1] = xi[i]
  z[i,2] = xi[i]**2
  z[i,3] = xi[i]**3
  z[i,4] = math.e

z

array([[ 1.00000000e+00,  1.00000000e+01,  1.00000000e+02,
         1.00000000e+03,  2.71828183e+00],
       [ 1.00000000e+00, -8.66666700e+00,  7.51111169e+01,
        -6.50963038e+02,  2.71828183e+00],
       [ 1.00000000e+00, -7.33333300e+00,  5.37777729e+01,
        -3.94370317e+02,  2.71828183e+00],
       [ 1.00000000e+00, -6.00000000e+00,  3.60000000e+01,
        -2.16000000e+02,  2.71828183e+00],
       [ 1.00000000e+00, -4.66666700e+00,  2.17777809e+01,
        -1.01629651e+02,  2.71828183e+00],
       [ 1.00000000e+00, -3.33333300e+00,  1.11111089e+01,
        -3.70370259e+01,  2.71828183e+00],
       [ 1.00000000e+00, -2.00000000e+00,  4.00000000e+00,
        -8.00000000e+00,  2.71828183e+00],
       [ 1.00000000e+00, -6.66667000e-01,  4.44444889e-01,
        -2.96296741e-01,  2.71828183e+00],
       [ 1.00000000e+00,  6.66667000e-01,  4.44444889e-01,
         2.96296741e-01,  2.71828183e+00],
       [ 1.00000000e+00,  2.00000000e+00,  4.00000000e+00,
         8.00000000e+00

In [ ]:
Zt = z.transpose()
Zt

array([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00],
       [ 1.00000000e+01, -8.66666700e+00, -7.33333300e+00,
        -6.00000000e+00, -4.66666700e+00, -3.33333300e+00,
        -2.00000000e+00, -6.66667000e-01,  6.66667000e-01,
         2.00000000e+00,  3.33333300e+00,  4.66666700e+00,
         6.00000000e+00,  7.33333300e+00,  8.66666700e+00,
         1.00000000e+01],
       [ 1.00000000e+02,  7.51111169e+01,  5.37777729e+01,
         3.60000000e+01,  2.17777809e+01,  1.11111089e+01,
         4.00000000e+00,  4.44444889e-01,  4.44444889e-01,
         4.00000000e+00,  1.11111089e+01,  2.17777809e+01,
         3.60000000e+01,  5.37777729e+01,  7.51111169e+01,
         1.00000000e+02],
       [ 1.00000000e+03, -6.50963038e

In [ ]:
ZtZ = np.dot(Zt,z)
print(ZtZ)
ZtY = np.dot(Zt,yi)
print(ZtY)

[[1.60000000e+01 2.00000000e+01 6.04444449e+02 2.00000000e+03
  4.34925093e+01]
 [2.00000000e+01 6.04444449e+02 2.00000000e+03 4.08873095e+04
  5.43656366e+01]
 [6.04444449e+02 2.00000000e+03 4.08873095e+04 2.00000000e+05
  1.64305036e+03]
 [2.00000000e+03 4.08873095e+04 2.00000000e+05 3.27540248e+06
  5.43656366e+03]
 [4.34925093e+01 5.43656366e+01 1.64305036e+03 5.43656366e+03
  1.18224898e+02]]
[  -1156.759431     -2369.67677241  -79784.38661291 -312399.13998111
   -3144.39814119]


In [ ]:
Coeffs = np.linalg.solve(ZtZ,ZtY)
print(Coeffs[2])

-2.117037252168999


##Question 4

In [9]:
def poweriterate(x,xlen):
  a = np.zeros(xlen)
  for q in range(xlen):
    a[q] = 1
  for r in range(10):
    xn = np.dot(x,a)
    nlambda = abs(xn).max()
    print(xn.max())
    x = x / xn.max()
  return nlambda

In [10]:
#This block of code creates matrix A and gives it values, nothing of note happens until next block
A = np.zeros([5,5])

A[0,0] = 6.437161
A[0,1] = 6.051567
A[0,2] = 5.608547
A[0,3] = 1.603539
A[0,4] = 5.086042

A[1,0] = 6.051567
A[1,1] = 0.308111
A[1,2] = 7.266994
A[1,3] = 3.607854
A[1,4] = 0.361327

A[2,0] = 5.608547
A[2,1] = 7.266994
A[2,2] = 2.829256
A[2,3] = 5.320674
A[2,4] = 0.546016

A[3,0] = 1.603539
A[3,1] = 3.607854
A[3,2] = 5.320674
A[3,3] = 2.023653
A[3,4] = 7.301783

A[4,0] = 5.086042
A[4,1] = 0.361327
A[4,2] = 0.546016
A[4,3] = 7.301783
A[4,4] = 1.839432

In [11]:
AInv = np.linalg.inv(A)
MaxEigen = poweriterate(A,5)
MinEigen = poweriterate(AInv,5)

24.786856
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.10616897829225831
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [12]:
ConNum = MaxEigen/MinEigen
print(ConNum)

1.0


##Question 5

In [ ]:
def xi(num,i,ub,lb):
  return lb+ i*(ub-lb)/(n-1)

def g(x):
  x0 = -5.75
  xsub = (x - x0)**2
  ans = 9*np.exp(-7*xsub)
  return ans

In [ ]:
def DEmat(num):
  mat = np.zeros((n,n))
  for i in range(n):
    mat[i][i] = -2
  for j in range(n-2):
    mat[j+1][j] = 1
    mat[j+1][j+2] = 1
  return mat

def ansMat(n,L,R,ub,lb):
  mat = np.zeros(n)
  mat[0] = -2*L
  mat[-1] = -2*R
  for i in range(1,n-1):
    deltax = xi(n,i,ub,lb)
    if i == 1:
      x = deltax
    else:
      x += (ub-lb)/(n-1)
    mat[i] = g(x) * (deltax**2)
  return mat

In [ ]:
upbound = -2
lowbound = -7
n = 10
yL = -7
yR = -7

aMat = DEmat(n)
gMat = ansMat(n,yL,yR,upbound,lowbound)

In [ ]:
yMat = np.linalg.solve(aMat,gMat)
yMat.min()

-542.6758085237539