# Lec 2 Gauss-Jordan

## Imports

In [1]:
import numpy as np

### Gauss-Jordan Program

In [53]:
dim = 4
matdim = (dim, dim+1)
amat = np.zeros(matdim)

In [54]:
amat[0,0] = 2
amat[0,1] = 2
amat[0,2] = 4
amat[0,3] = -2
amat[0,4] = 10

In [55]:
amat[1,0] = 1
amat[1,1] = 3
amat[1,2] = 2
amat[1,3] = 4
amat[1,4] = 17

In [56]:
amat[2,0] = 3
amat[2,1] = 1
amat[2,2] = 3
amat[2,3] = 1
amat[2,4] = 18

In [57]:
amat[3,0] = 1
amat[3,1] = 3
amat[3,2] = 4
amat[3,3] = 2
amat[3,4] = 27

In [58]:
amat

array([[ 2.,  2.,  4., -2., 10.],
       [ 1.,  3.,  2.,  4., 17.],
       [ 3.,  1.,  3.,  1., 18.],
       [ 1.,  3.,  4.,  2., 27.]])

#### Elim

first row where i = 0 :)

In [59]:
pivot = amat[0,0]

In [60]:
# need amat[1,0] = 0 after this 
ratio = amat[1,0]/amat[0,0]
amat[1,0] -= amat[0,0]*ratio
amat[1,1] -= amat[0,1]*ratio
amat[1,2] -= amat[0,2]*ratio
amat[1,3] -= amat[0,3]*ratio
amat[1,4] -= amat[0,4]*ratio
ratio = amat[2,0]/amat[0,0]
amat[2,0] -= amat[0,0]*ratio
amat[2,1] -= amat[0,1]*ratio
amat[2,2] -= amat[0,2]*ratio
amat[2,3] -= amat[0,3]*ratio
amat[2,4] -= amat[0,4]*ratio
ratio = amat[3,0]/amat[0,0]
amat[3,0] -= amat[0,0]*ratio
amat[3,1] -= amat[0,1]*ratio
amat[3,2] -= amat[0,2]*ratio
amat[3,3] -= amat[0,3]*ratio
amat[3,4] -= amat[0,4]*ratio
amat

array([[ 2.,  2.,  4., -2., 10.],
       [ 0.,  2.,  0.,  5., 12.],
       [ 0., -2., -3.,  4.,  3.],
       [ 0.,  2.,  2.,  3., 22.]])

In [61]:
ratio = amat[2,1]/amat[1,1]
amat[2,1] -= amat[1,1]*ratio
amat[2,2] -= amat[1,2]*ratio
amat[2,3] -= amat[1,3]*ratio
amat[2,4] -= amat[1,4]*ratio
ratio = amat[3,1]/amat[1,1]
amat[3,1] -= amat[1,1]*ratio
amat[3,2] -= amat[1,2]*ratio
amat[3,3] -= amat[1,3]*ratio
amat[3,4] -= amat[1,4]*ratio
amat

array([[ 2.,  2.,  4., -2., 10.],
       [ 0.,  2.,  0.,  5., 12.],
       [ 0.,  0., -3.,  9., 15.],
       [ 0.,  0.,  2., -2., 10.]])

In [62]:
ratio = amat[3,2]/amat[2,2]
amat[3,2] -= amat[2,2]*ratio
amat[3,3] -= amat[2,3]*ratio
amat[3,4] -= amat[2,4]*ratio
amat

array([[ 2.,  2.,  4., -2., 10.],
       [ 0.,  2.,  0.,  5., 12.],
       [ 0.,  0., -3.,  9., 15.],
       [ 0.,  0.,  0.,  4., 20.]])

In [64]:
x4 = amat[3,4]/amat[3,3]
x4

5.0

In [67]:
x3 = (amat[2,4]-amat[2,3]*x4)/amat[2,2]
x3

10.0

In [68]:
x2 = (amat[1,4]-amat[1,3]*x4-amat[1,2]*x3)/amat[1,1]
x2

-6.5

In [71]:
x1 = (amat[0,4]-amat[0,3]*x4-amat[0,2]*x3-amat[0,1]*x2)/amat[0,0]
x1

-3.5